### ISSUE TITLE
getLyrics() return null

### ISSUE THREAD

**Issue by N1C0exe** [roogue/rlyrics#3]
Seems that getLyrics() return null

**Comment by roogue** [comment]
> Seems that getLyrics() return null 

Hi Nico, the function returns null is probably due to the changes of structure of the website. However, this issue would not be fixed due to this project being no longer maintained. You may switch to some other packages which provide more effective and stable functionality. Thanks.

**Comment by N1C0exe** [comment]
> > Seems that getLyrics() return null
> 
> Hi Nico, the function returns null is probably due to the changes of structure of the website. However, this issue would not be fixed due to this project being no longer maintained. You may switch to some other packages which provide more effective and stable functionality. Thanks.

Nuu I have searched for a nice lyrics lib and this for a week worked , but today im reciving null . ( so yes for one week worked fine )

**Comment by roogue** [comment]
I am actually surprised that this package still works after a year of inactivity. Since this package uses web-scraping method, a slight change in the musixmatch website (change in class name/element id/URL path) would break the whole functionality, and it is time-draining to fix the issue (due to how poorly I wrote this package a year ago hehe). So yeah, as I said, you should just switch to some other packages, I am not maintaining this library anymore. FYI, you can steal the idea/code of this library and make one yourself! I don't mind!

**Comment by N1C0exe** [comment]
> I am actually surprised that this package still works after a year of inactivity. Since this package uses web-scraping method, a slight change in the musixmatch website (change in class name/element id/URL path) would break the whole functionality, and it is time-draining to fix the issue (due to how poorly I wrote this package a year ago hehe). So yeah, as I said, you should just switch to some other packages, I am not maintaining this library anymore. FYI, you can steal the idea/code of this library and make one yourself! I don't mind!

Now work again haahah. I dont know what happened xD

**Comment by roogue** [comment]
Glad to hear that it works again :) Good for you.
